### ISSUE TITLE
Page admin showing each extension twice, breaks admin page

### ISSUE THREAD

**Issue by danpalmer** [feincms/feincms#620] opened 2016-02-03 10:10 UTC
We've just started setting up a FeinCMS based blog, but have encountered a small problem.

We set up the Page model in the normal way, and register a few extensions like this:

```python
Page.register_extensions(
    'feincms.module.extensions.datepublisher',
    'feincms.module.page.extensions.excerpt',
    'feincms.module.page.extensions.relatedpages',
)
```

The extensions appear to only be loaded once - that line of code is run once, no "AlreadyRegistered" exceptions, and the migrations all work fine which implies the model is being created properly.

However, the admin shows two tabs for each extension. The tabs contain the same content, but only one (non-deterministic) tab will work at any time, which means you have to enter data twice in the admin to be sure that it will save. Also some widgets in the repeated tabs just don't work, an example of this is the multiple selection widget for the "relatedpages" extension.

I don't know enough about FeinCMS to know where to even begin looking for what might be causing this. Does anyone have any ideas about what might be causing this, or even a good place to start looking?

**Comment by matthiask** [comment] 2016-02-03 10:49
Thanks for the report! Which version of FeinCMS and Django are you using?

Sounds like something that should be immediately fixed.

**Comment by danpalmer** [comment] 2016-02-03 10:54
Hi, Django 1.9.1 and FeinCMS 1.11.4. I can test on 1.9.2 soon as well, but I don't remember anything in the release notes that would affect this.

**Comment by matthiask** [comment] 2016-02-03 10:57
Thanks! I'll have a look at this later today.

**Comment by mjl** [comment] 2016-02-03 10:57
Does the browser Javascript Console show any errors?

**Comment by danpalmer** [comment] 2016-02-03 11:03
@mjl Yes, when I use "relatedpages", I get the following error:

```
Uncaught TypeError: Cannot read property 'id' of null
    window.SelectFilter.init	@	SelectFilter2.js:24
      (anonymous function)	@	VM5379:1
```

This appears to be an issue with there being two of the same multiple selection widgets on the page, but I'm not certain.

**Comment by matthiask** [comment] 2016-02-03 11:39
It seems that for some reason the initialization of the selectbox is run twice. 

`SelectFilter2.js` renames the old select box to `<name>_old`, therefore the element cannot be found anymore, and that's the reason for the JavaScript error above. Probably Django's `addEvent` is run twice:

- First when parsing the HTML
- Afterwards when reinserting the HTML when building the tabbed interface (https://github.com/feincms/feincms/blob/master/feincms/static/feincms/item_editor.js#L398) — @mjl we should probably not reinsert the HTML, but instead reinsert the DOM nodes directly with `$.fn.append` or `node.appendChild`...

**Comment by matthiask** [comment] 2016-02-03 11:42
... unfortunately I still can't reproduce the problem with extension tabs appearing twice.

**Comment by mjl** [comment] 2016-02-03 11:45
> It seems that for some reason the initialization of the selectbox is run twice.

  I've seen that message in the console for quite some while, it doesn't appear to be harmful though. More a red herring I'm afraid.

**Comment by danpalmer** [comment] 2016-02-03 11:55
Some more info that might help... We override `item_editor.html` to add a conditional on whether there are translations available, since we a) don't use translations, and b) raise template syntax errors on any missing template variables, however this doesn't appear to make a difference (I've tried not overriding it, and we still have the issue).

**Comment by matthiask** [comment] 2016-02-03 12:05
If I modify `relatedpages.py` to call `add_extension_options` twice I get the same problem. But why should `relatedpages.Extension.handle_modeladmin` and friends be called twice?

![screen shot 2016-02-03 at 13 04 21](https://cloud.githubusercontent.com/assets/2627/12781784/ccd73f8a-ca76-11e5-81ef-fd305b5195ab.png)

**Comment by danpalmer** [comment] 2016-02-03 12:38
Ok, I think I'm getting closer to finding the issue. I haven't confirmed this yet, but:

FeinCMS registers the `Page` with the default admin site, however we use a custom admin site instance. When autodiscover is on for admin modules, Django reads in FeinCMS's `admin.py` and causes the registration to happen to the default site, which we don't use. Our own registering to our custom admin site is then a second load, which is causing the extensions to be loaded twice.

I'm not sure what the solution here is. We are trying to disable autodiscover as we don't want it, but I guess the ultimate aim for FeinCMS would be to support custom admin sites, with and without autodiscover.

**Comment by matthiask** [comment] 2016-02-03 12:44
Great! Is there a reason why you can't just set `FEINCMS_USE_PAGE_ADMIN = False` in your settings?

This would of course still mean that FeinCMS pages cannot be used in more than one admin site at the same time...

**Comment by danpalmer** [comment] 2016-02-03 13:38
Ah, that looks perfect! We hadn't seen that in the documentation. Thanks!

**Comment by matthiask** [comment] 2016-02-03 15:44
It's not even mentioned in the page documentation, only under `settings`. Does it work?

**Comment by matthiask** [comment] 2016-02-04 15:26
@danpalmer Does it work for you now? If yes we should document this, and also document `FEINCMS_USE_PAGE_ADMIN`.

**Comment by matthiask** [comment] 2016-02-04 20:00
The TypeError above is fixed in https://github.com/feincms/feincms/commit/ed973ac9c3ccbfca5c8b8bbc11e02c68d9978933.

Some documentation has been added in https://github.com/feincms/feincms/commit/94ffa872ac0a3addca8a8f8b26860b96f66826bd#diff-3fd23e085e479501733d484b109d838aR91

Closing this issue. @danpalmer Please reopen if things do not work for you. Thanks!

**Closed by matthiask** 2016-02-04 20:00 UTC
Labels: documentation
